# Generated by Django 5.2.3 on 2025-06-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UDPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='0.0.0.0', max_length=100)),
                ('port', models.IntegerField(default=6666)),
            ],
        ),
    ]
